name: CI

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install requests
    - name: Generate report
      run: bash ./run.sh
    - name: Deploy GitHub pages
      run: |
        export GITHUB_TOKEN=${{ secrets.ACCESS_TOKEN }}
        export GITHUB_DEPLOY_KEY=${{ secrets.DEPLOY_KEY }}
        bash ./configs/ghactions/deploy_github_pages.sh
